import crypto from 'crypto';
import mammoth from 'mammoth';
import { parsePdf } from './pdfParser.js';
import { parseSectionsFromText } from './sectionDetector.js';

/**
 * Universal Academic Document Parser
 * Supports PDF, DOC, DOCX, PPT, PPTX, and TXT files.
 * Computes deterministic SHA-256 file hashes for duplicate detection.
 */

export function calculateFileHash(bufferOrString) {
  if (!bufferOrString) return '';
  const hash = crypto.createHash('sha256');
  if (Buffer.isBuffer(bufferOrString)) {
    hash.update(bufferOrString);
  } else {
    hash.update(String(bufferOrString), 'utf-8');
  }
  return hash.digest('hex');
}

export async function parseDocument(fileBuffer, originalFilename = 'document.pdf') {
  const ext = (originalFilename || 'document.pdf').split('.').pop().toLowerCase();
  const fileHash = calculateFileHash(fileBuffer || originalFilename);

  let cleanText = '';
  let pages = [];
  let isScanned = false;
  let totalPages = 1;
  let errorMessage = null;

  try {
    if (ext === 'pdf') {
      if (typeof fileBuffer === 'string' && !fileBuffer.startsWith('%PDF')) {
        cleanText = fileBuffer.trim();
      } else {
        const pdfResult = await parsePdf(fileBuffer, originalFilename);
        if (!pdfResult.success) {
          if (typeof fileBuffer === 'string' || (Buffer.isBuffer(fileBuffer) && !fileBuffer.toString('utf-8', 0, 5).includes('%PDF'))) {
            cleanText = (fileBuffer ? fileBuffer.toString('utf-8') : '').trim();
          } else {
            return {
              success: false,
              isScanned: true,
              filename: originalFilename,
              format: ext,
              fileHash,
              characterCount: pdfResult.characterCount || 0,
              totalPages: pdfResult.totalPages || 0,
              pages: [],
              sections: [],
              extractedTitle: originalFilename.replace(/\.pdf$/i, '').replace(/[_-]+/g, ' '),
              text: '',
              error: pdfResult.errorMessage || 'This PDF appears to contain scanned/image pages. Text extraction could not retrieve sufficient content.',
            };
          }
        } else {
          cleanText = pdfResult.text;
          pages = pdfResult.pages;
          totalPages = pdfResult.totalPages;
        }
      }
    } else if (ext === 'docx' || ext === 'doc') {
      try {
        if (Buffer.isBuffer(fileBuffer)) {
          const mammothResult = await mammoth.extractRawText({ buffer: fileBuffer });
          cleanText = (mammothResult.value || '').trim();
        } else if (typeof fileBuffer === 'string') {
          cleanText = fileBuffer.trim();
        }
      } catch (docErr) {
        if (typeof fileBuffer === 'string') {
          cleanText = fileBuffer;
        } else if (Buffer.isBuffer(fileBuffer)) {
          cleanText = fileBuffer.toString('utf-8');
        }
      }
    } else if (ext === 'txt' || ext === 'md' || ext === 'text') {
      if (Buffer.isBuffer(fileBuffer)) {
        cleanText = fileBuffer.toString('utf-8').trim();
      } else {
        cleanText = String(fileBuffer || '').trim();
      }
    } else {
      // PPT / PPTX or other formats
      if (Buffer.isBuffer(fileBuffer)) {
        cleanText = fileBuffer.toString('utf-8').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, ' ').trim();
      } else {
        cleanText = String(fileBuffer || '').trim();
      }
    }

    // Clean text
    cleanText = cleanText
      .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, ' ')
      .replace(/\r\n/g, '\n')
      .replace(/[ \t]+/g, ' ')
      .trim();

    // Check if sufficient text was extracted
    if (cleanText.length < 50) {
      return {
        success: false,
        isScanned: true,
        filename: originalFilename,
        format: ext,
        fileHash,
        characterCount: cleanText.length,
        totalPages: 0,
        pages: [],
        sections: [],
        extractedTitle: originalFilename.replace(/\.[^/.]+$/, '').replace(/[_-]+/g, ' '),
        text: '',
        error: 'This PDF appears to contain scanned/image pages. Text extraction could not retrieve sufficient content.',
      };
    }

    // If pages array wasn't generated by PDF parser, construct pages from text
    if (pages.length === 0) {
      const pageSize = 1800;
      totalPages = Math.max(1, Math.ceil(cleanText.length / pageSize));
      for (let i = 0; i < totalPages; i++) {
        pages.push({
          pageNumber: i + 1,
          text: cleanText.slice(i * pageSize, (i + 1) * pageSize).trim(),
        });
      }
    }

    // Detect structured sections from text
    const detectedSections = parseSectionsFromText(cleanText);

    // Extract genuine title from the first lines of text if available
    let extractedTitle = originalFilename
      .replace(/\.(pdf|docx?|pptx?|txt|md)$/i, '')
      .replace(/[_-]+/g, ' ')
      .trim();

    const firstNonEmptyLine = cleanText.split('\n').map(l => l.trim()).filter(l => l.length > 5 && l.length < 150 && !/^(abstract|introduction|ieee|volume|issue|page|\d+)/i.test(l))[0];
    if (firstNonEmptyLine && firstNonEmptyLine.length > 10) {
      extractedTitle = firstNonEmptyLine;
    }

    return {
      success: true,
      isScanned: false,
      filename: originalFilename,
      format: ext,
      fileHash,
      characterCount: cleanText.length,
      totalPages: pages.length || totalPages,
      pages,
      sections: detectedSections,
      extractedTitle,
      text: cleanText,
    };
  } catch (err) {
    console.error(`[documentParser] Extraction failure for ${originalFilename}:`, err.message);
    return {
      success: false,
      isScanned: false,
      filename: originalFilename,
      format: ext,
      fileHash,
      characterCount: 0,
      totalPages: 0,
      pages: [],
      sections: [],
      extractedTitle: originalFilename,
      text: '',
      error: `Failed to extract text from document: ${err.message}`,
    };
  }
}

export default {
  calculateFileHash,
  parseDocument,
};
